module_maker = "ModuleBuild"

[build]
build_class = "builder::MyBuilder"

[no_index]
directory = ['t', 'xt', 'inc', 'share', 'eg', 'examples', 'author', 'builder', 'deps']

[unsupported]
os = [
    "MSWin32"
]

[XSUtil]
generate_ppport_h = 1
